//todo not sure this will work, becuase you have 4 V1 files, reach file should have different version
CREATE TABLE candidate
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(15)                             NOT NULL,
    last_name  VARCHAR(15)                             NOT NULL,
    number     INTEGER                                 NOT NULL,
    CONSTRAINT pk_candidate PRIMARY KEY (id)
);
