CREATE TABLE election_location
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address VARCHAR(15)                             NOT NULL,
    CONSTRAINT pk_election_location PRIMARY KEY (id)
);
