CREATE TABLE elector
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name      VARCHAR(15) NOT NULL,
    last_name       VARCHAR(15) NOT NULL,
    date_of_birth   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    passport_number VARCHAR(20),
    CONSTRAINT pk_elector PRIMARY KEY (id)
);
