CREATE TABLE vote
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    elector_id           BIGINT                                  NOT NULL,
    election_location_id BIGINT                                  NOT NULL,
    candidate_id         BIGINT                                  NOT NULL,

    CONSTRAINT pk_vote PRIMARY KEY (id),

    CONSTRAINT fk_elector FOREIGN KEY (elector_id) REFERENCES elector (id),
    CONSTRAINT fk_election_location FOREIGN KEY (election_location_id) REFERENCES election_location (id),
    CONSTRAINT fk_candidate FOREIGN KEY (candidate_id) REFERENCES candidate (id)
);